"""Trial build expiration.

Soft commercial gate for prebuilt trial binaries. The trial .spec writes a
gitignored _trial_stamp.py at build time (same pattern as _version.py), so
the expiry is always build date + trial length with no code edits. Regular
builds and source checkouts have no stamp, which leaves every trial check
inert.
"""
from __future__ import annotations

from datetime import date
from typing import Optional

try:
    from _trial_stamp import BUILT, EXPIRY  # generated by the trial .spec
    TRIAL_BUILD_DATE: Optional[date] = date.fromisoformat(BUILT)
    TRIAL_EXPIRY_DATE: Optional[date] = date.fromisoformat(EXPIRY)
except ImportError:
    TRIAL_BUILD_DATE = None
    TRIAL_EXPIRY_DATE = None


def is_trial() -> bool:
    return TRIAL_EXPIRY_DATE is not None


def days_remaining(today: Optional[date] = None) -> int:
    """Days until expiry. Zero on the expiry date itself, negative once expired."""
    if TRIAL_EXPIRY_DATE is None:
        return 0
    today = today or date.today()
    return (TRIAL_EXPIRY_DATE - today).days


def is_expired(today: Optional[date] = None) -> bool:
    if TRIAL_EXPIRY_DATE is None:
        return False
    today = today or date.today()
    if TRIAL_BUILD_DATE is not None and today < TRIAL_BUILD_DATE:
        return True  # system clock set before the build date
    return (TRIAL_EXPIRY_DATE - today).days < 0
